# The base image includes FSL tool and PreFreeSurfer pipeline on CentOS7
FROM bigdatalabteam/hcp-prefreesurfer:exec-centos7-reprozip.fslbuild-centos5

# Installing spot tool
#RUN yum -y update; yum clean all 
RUN yum clean all &&\
    yum -y install epel-release which; yum clean all &&\
    yum -y install python3-pip; yum clean all

RUN cd /tmp/ &&\
    git clone https://github.com/ali4006/spot.git; yum clean all &&\
    pip3 install --no-cache-dir spot/lightspot/

RUN chown 1000:1000 /tmp

